name: C/C++ CI

on:
  push:
    branches: [ arrow-12.0 ]
  pull_request:
    branches: [ arrow-12.0 ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
